// Left Nav
export const VERTICAL_LINE_HEIGHT_LEFT = 26.5;
export const VERTICAL_LINE_HEIGHT_LEFT_MOBILE = 20;
export const VERTICAL_LINE_OFFSET_X_LEFT = 2.5;
export const VERTICAL_LINE_OFFSET_X_LEFT_MOBILE = 1;
export const VERTICAL_LINE_OFFSET_Y_LEFT = 1.7;
export const VERTICAL_LINE_OFFSET_Y_LEFT_MOBILE = 1;

export const HORIZONTAL_LINE_WIDTH_LEFT = 19.3;
export const HORIZONTAL_LINE_OFFSET_X_LEFT = 1.2;
export const HORIZONTAL_LINE_OFFSET_X_LEFT_MOBILE = 0.5;
export const HORIZONTAL_LINE_OFFSET_Y_LEFT = 6.5;

// Right Nav
export const VERTICAL_LINE_HEIGHT_RIGHT = 26.5;
export const VERTICAL_LINE_HEIGHT_RIGHT_MOBILE = 20;
export const VERTICAL_LINE_OFFSET_X_RIGHT = 2.5;
export const VERTICAL_LINE_OFFSET_X_RIGHT_MOBILE = 1;
export const VERTICAL_LINE_OFFSET_Y_RIGHT = 1.7;
export const VERTICAL_LINE_OFFSET_Y_RIGHT_MOBILE = 1;

export const HORIZONTAL_LINE_WIDTH_RIGHT = 23;
export const HORIZONTAL_LINE_OFFSET_X_RIGHT = 1.2;
export const HORIZONTAL_LINE_OFFSET_X_RIGHT_MOBILE = 0.5;
export const HORIZONTAL_LINE_OFFSET_Y_RIGHT = 6.5;
