// Left Nav
export const VERTICAL_LINE_HEIGHT_LEFT = 30;
export const VERTICAL_LINE_HEIGHT_LEFT_MOBILE = 20;
export const VERTICAL_LINE_OFFSET_X_LEFT = 3;
export const VERTICAL_LINE_OFFSET_X_LEFT_MOBILE = 1;
export const VERTICAL_LINE_OFFSET_Y_LEFT = 2;
export const VERTICAL_LINE_OFFSET_Y_LEFT_MOBILE = 1;

export const HORIZONTAL_LINE_WIDTH_LEFT = 25;
export const HORIZONTAL_LINE_OFFSET_X_LEFT = 1.5;
export const HORIZONTAL_LINE_OFFSET_X_LEFT_MOBILE = 0.5;
export const HORIZONTAL_LINE_OFFSET_Y_LEFT = 8;

// Right Nav
export const VERTICAL_LINE_HEIGHT_RIGHT = 30;
export const VERTICAL_LINE_HEIGHT_RIGHT_MOBILE = 20;
export const VERTICAL_LINE_OFFSET_X_RIGHT = 3;
export const VERTICAL_LINE_OFFSET_X_RIGHT_MOBILE = 1;
export const VERTICAL_LINE_OFFSET_Y_RIGHT = 2;
export const VERTICAL_LINE_OFFSET_Y_RIGHT_MOBILE = 1.2;

export const HORIZONTAL_LINE_WIDTH_RIGHT = 30;
export const HORIZONTAL_LINE_OFFSET_X_RIGHT = 1.5;
export const HORIZONTAL_LINE_OFFSET_X_RIGHT_MOBILE = 0.5;
export const HORIZONTAL_LINE_OFFSET_Y_RIGHT = 8;
